apiVersion: v1
kind: Service
metadata:
  name: devopsscaffoldnodejs
  namespace: devopsscaffoldnodejs
spec:
  type: LoadBalancer
  selector:
    app: devopsscaffoldnodejs
  ports:
    - name: http
      port: 6060
      protocol: TCP
      targetPort: http